//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWebClient.EmployeeRegistrationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Webservice.app.com", ConfigurationName="EmployeeRegistrationService.EmployeeregistrationPortType")]
    public interface EmployeeregistrationPortType {
        
        // CODEGEN: Parameter 'username' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:loginAdmin", ReplyAction="urn:loginAdminResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HospitalWebClient.EmployeeRegistrationService.loginAdminResponse loginAdmin(HospitalWebClient.EmployeeRegistrationService.loginAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:loginAdmin", ReplyAction="urn:loginAdminResponse")]
        System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.loginAdminResponse> loginAdminAsync(HospitalWebClient.EmployeeRegistrationService.loginAdminRequest request);
        
        // CODEGEN: Parameter 'username' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:edit", ReplyAction="urn:editResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HospitalWebClient.EmployeeRegistrationService.editResponse edit(HospitalWebClient.EmployeeRegistrationService.editRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:edit", ReplyAction="urn:editResponse")]
        System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.editResponse> editAsync(HospitalWebClient.EmployeeRegistrationService.editRequest request);
        
        // CODEGEN: Parameter 'username' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:login", ReplyAction="urn:loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HospitalWebClient.EmployeeRegistrationService.loginResponse login(HospitalWebClient.EmployeeRegistrationService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:login", ReplyAction="urn:loginResponse")]
        System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.loginResponse> loginAsync(HospitalWebClient.EmployeeRegistrationService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:delete")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:delete")]
        System.Threading.Tasks.Task deleteAsync(int id);
        
        // CODEGEN: Parameter 'username' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:register", ReplyAction="urn:registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HospitalWebClient.EmployeeRegistrationService.registerResponse register(HospitalWebClient.EmployeeRegistrationService.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:register", ReplyAction="urn:registerResponse")]
        System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.registerResponse> registerAsync(HospitalWebClient.EmployeeRegistrationService.registerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginAdmin", WrapperNamespace="http://Webservice.app.com", IsWrapped=true)]
    public partial class loginAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public loginAdminRequest() {
        }
        
        public loginAdminRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginAdminResponse", WrapperNamespace="http://Webservice.app.com", IsWrapped=true)]
    public partial class loginAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=0)]
        public int @return;
        
        public loginAdminResponse() {
        }
        
        public loginAdminResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://Webservice.app.com", IsWrapped=true)]
    public partial class editRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public editRequest() {
        }
        
        public editRequest(int id, string username, string password) {
            this.id = id;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editResponse", WrapperNamespace="http://Webservice.app.com", IsWrapped=true)]
    public partial class editResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=0)]
        public int @return;
        
        public editResponse() {
        }
        
        public editResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://Webservice.app.com", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public loginRequest() {
        }
        
        public loginRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://Webservice.app.com", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=0)]
        public int @return;
        
        public loginResponse() {
        }
        
        public loginResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://Webservice.app.com", IsWrapped=true)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public registerRequest() {
        }
        
        public registerRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://Webservice.app.com", IsWrapped=true)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice.app.com", Order=0)]
        public int @return;
        
        public registerResponse() {
        }
        
        public registerResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeregistrationPortTypeChannel : HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeregistrationPortTypeClient : System.ServiceModel.ClientBase<HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType>, HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType {
        
        public EmployeeregistrationPortTypeClient() {
        }
        
        public EmployeeregistrationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeregistrationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeregistrationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeregistrationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HospitalWebClient.EmployeeRegistrationService.loginAdminResponse HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType.loginAdmin(HospitalWebClient.EmployeeRegistrationService.loginAdminRequest request) {
            return base.Channel.loginAdmin(request);
        }
        
        public int loginAdmin(string username, string password) {
            HospitalWebClient.EmployeeRegistrationService.loginAdminRequest inValue = new HospitalWebClient.EmployeeRegistrationService.loginAdminRequest();
            inValue.username = username;
            inValue.password = password;
            HospitalWebClient.EmployeeRegistrationService.loginAdminResponse retVal = ((HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType)(this)).loginAdmin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.loginAdminResponse> HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType.loginAdminAsync(HospitalWebClient.EmployeeRegistrationService.loginAdminRequest request) {
            return base.Channel.loginAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.loginAdminResponse> loginAdminAsync(string username, string password) {
            HospitalWebClient.EmployeeRegistrationService.loginAdminRequest inValue = new HospitalWebClient.EmployeeRegistrationService.loginAdminRequest();
            inValue.username = username;
            inValue.password = password;
            return ((HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType)(this)).loginAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HospitalWebClient.EmployeeRegistrationService.editResponse HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType.edit(HospitalWebClient.EmployeeRegistrationService.editRequest request) {
            return base.Channel.edit(request);
        }
        
        public int edit(int id, string username, string password) {
            HospitalWebClient.EmployeeRegistrationService.editRequest inValue = new HospitalWebClient.EmployeeRegistrationService.editRequest();
            inValue.id = id;
            inValue.username = username;
            inValue.password = password;
            HospitalWebClient.EmployeeRegistrationService.editResponse retVal = ((HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType)(this)).edit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.editResponse> HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType.editAsync(HospitalWebClient.EmployeeRegistrationService.editRequest request) {
            return base.Channel.editAsync(request);
        }
        
        public System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.editResponse> editAsync(int id, string username, string password) {
            HospitalWebClient.EmployeeRegistrationService.editRequest inValue = new HospitalWebClient.EmployeeRegistrationService.editRequest();
            inValue.id = id;
            inValue.username = username;
            inValue.password = password;
            return ((HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType)(this)).editAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HospitalWebClient.EmployeeRegistrationService.loginResponse HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType.login(HospitalWebClient.EmployeeRegistrationService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public int login(string username, string password) {
            HospitalWebClient.EmployeeRegistrationService.loginRequest inValue = new HospitalWebClient.EmployeeRegistrationService.loginRequest();
            inValue.username = username;
            inValue.password = password;
            HospitalWebClient.EmployeeRegistrationService.loginResponse retVal = ((HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.loginResponse> HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType.loginAsync(HospitalWebClient.EmployeeRegistrationService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.loginResponse> loginAsync(string username, string password) {
            HospitalWebClient.EmployeeRegistrationService.loginRequest inValue = new HospitalWebClient.EmployeeRegistrationService.loginRequest();
            inValue.username = username;
            inValue.password = password;
            return ((HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType)(this)).loginAsync(inValue);
        }
        
        public void delete(int id) {
            base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HospitalWebClient.EmployeeRegistrationService.registerResponse HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType.register(HospitalWebClient.EmployeeRegistrationService.registerRequest request) {
            return base.Channel.register(request);
        }
        
        public int register(string username, string password) {
            HospitalWebClient.EmployeeRegistrationService.registerRequest inValue = new HospitalWebClient.EmployeeRegistrationService.registerRequest();
            inValue.username = username;
            inValue.password = password;
            HospitalWebClient.EmployeeRegistrationService.registerResponse retVal = ((HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType)(this)).register(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.registerResponse> HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType.registerAsync(HospitalWebClient.EmployeeRegistrationService.registerRequest request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<HospitalWebClient.EmployeeRegistrationService.registerResponse> registerAsync(string username, string password) {
            HospitalWebClient.EmployeeRegistrationService.registerRequest inValue = new HospitalWebClient.EmployeeRegistrationService.registerRequest();
            inValue.username = username;
            inValue.password = password;
            return ((HospitalWebClient.EmployeeRegistrationService.EmployeeregistrationPortType)(this)).registerAsync(inValue);
        }
    }
}
